Erp.App/Components/BOMCategoryUIViewComponent.cs
using Erp.Core.Services.Merchandising;
using Erp.Infrastructure;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Erp.App.Components
{
    public class BOMCategoryUIViewComponent : ViewComponent
    {
        private readonly MerchandisingService _service;
        public BOMCategoryUIViewComponent(InfrastructureDbContext db, IHttpContextAccessor httpContextAccessor)
        {
            _service = new MerchandisingService(db, httpContextAccessor.HttpContext);
        }

        public IViewComponentResult Invoke(int RawCategoryId, int StyleId, int TotalPeice,int TypeID)
        {
            ViewBag.SubCategoryList1 = new SelectList(_service.DDLRawCategoryItemByCatID(RawCategoryId), "Value", "Text");
            ViewBag.CurrencyList = new SelectList(_service.CurrencyDropDownList(), "Value", "Text");
            var model = new VMStyleView();
            model.vmBOM = new VMBOM();
            model.vmBOM = _service.BOMGetByStyleID(StyleId, RawCategoryId);
            model.vmBOM.Common_RawCategoryFK = RawCategoryId;
            model.vmBOM.Merchandising_StyleFK = StyleId;
            model.vmBOM.TotalPiece = TotalPeice;
            model.vmBOM.RawCategory = _service.GetCategory(RawCategoryId);
            model.TypeID = TypeID;
            switch (TypeID)
            {
                case 1: return View(model);
                case 2: return View("BOMFabricUI",model);
                case 3: return View("BOMChargeUI", model);
                case 4: return View("BOMAccessoriesUI", model);
                default: return View();
            }
        }
    }
}

Erp.App/Components/BOMFabricItemUIViewComponent.cs
using Erp.Core.Services.Merchandising;
using Erp.Infrastructure;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Erp.App.Components
{
    public class BOMFabricItemUIViewComponent : ViewComponent
    {
        private readonly MerchandisingService _service;
        public BOMFabricItemUIViewComponent(InfrastructureDbContext db, IHttpContextAccessor httpContextAccessor)
        {
            _service = new MerchandisingService(db, httpContextAccessor.HttpContext);
        }

        public IViewComponentResult Invoke(int ID, int RawCategoryId, int StyleId, int TotalPeice)
        {
            ViewBag.SubCategoryList1 = new SelectList(_service.DDLRawCategoryItemByCatID(RawCategoryId), "Value", "Text");
            ViewBag.ColorList = new SelectList(_service.ColorDropDownList(), "Value", "Text");
            ViewBag.CurrencyList = new SelectList(_service.CurrencyDropDownList(), "Value", "Text");
            var model = new VMStyleView();
            model.vmBOM = new VMBOM();
            if (ID != 0)
            {
                model.ActionId = 2;
                model.vmBOM = _service.BOMItemGetByID(ID);
                model.vmBOM.TotalPiece = TotalPeice;
            }
            else
            {
                model.vmBOM.Common_RawCategoryFK = RawCategoryId;
                model.vmBOM.Merchandising_StyleFK = StyleId;
                model.vmBOM.TotalPiece = TotalPeice;
                model.ActionId = 1;
            }
            return View(model);
        }
    }
}

Erp.App/Components/BOMFabricUIViewComponent.cs
using Erp.Core.Services.Merchandising;
using Erp.Infrastructure;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Erp.App.Components
{
    public class BOMFabricUIViewComponent : ViewComponent
    {
        private readonly MerchandisingService _service;
        public BOMFabricUIViewComponent(InfrastructureDbContext db, IHttpContextAccessor httpContextAccessor)
        {
            _service = new MerchandisingService(db,httpContextAccessor.HttpContext);
        }

        public IViewComponentResult Invoke(int ID, int RawCategoryId, int StyleId, int TotalPeice)
        {
            ViewBag.SubCategoryList1 = new SelectList(_service.DDLRawCategoryItemByCatID(RawCategoryId), "Value", "Text");
            var model = new VMStyleView();
            model.vmBOM = new VMBOM();
            model.vmBOM = _service.BOMGetByStyleID(StyleId, RawCategoryId);
            model.vmBOM.Common_RawCategoryFK = RawCategoryId;
            model.vmBOM.Merchandising_StyleFK = StyleId;
            model.vmBOM.TotalPiece = TotalPeice;
            model.vmBOM.RawCategory = _service.GetCategory(RawCategoryId);
            return View(model);
        }
    }
}

Erp.App/Components/BOMItemUIViewComponent.cs
using Erp.Core.Services.Merchandising;
using Erp.Infrastructure;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Erp.App.Components
{
    public class BOMItemUIViewComponent : ViewComponent
    {
        private readonly MerchandisingService _service;
        public BOMItemUIViewComponent(InfrastructureDbContext db, IHttpContextAccessor httpContextAccessor)
        {
            _service = new MerchandisingService(db, httpContextAccessor.HttpContext);
        }

        public IViewComponentResult Invoke(int ID,int RawCategoryId, int StyleId,int TotalPeice,int TypeID)
        {
            ViewBag.FabricList = new SelectList(_service.DDLBOMFabricByStyleID(StyleId), "Value", "Text");
            ViewBag.SubCategoryList1 = new SelectList(_service.DDLRawCategoryItemByCatID(RawCategoryId), "Value", "Text");
            ViewBag.CurrencyList = new SelectList(_service.CurrencyDropDownList(), "Value", "Text");
            ViewBag.ColorList = new SelectList(_service.ColorDropDownList(), "Value", "Text");
            ViewBag.SizeList = new SelectList(_service.DDLSizeByStyleID(StyleId), "Value", "Text");
            var model = new VMStyleView();
            model.vmBOM = new VMBOM();
            switch (TypeID)
            {
                case 1:
                    if (ID != 0)
                    {
                        model.ActionId = 2;
                        model.vmBOM = _service.BOMItemGetByID(ID);
                    }
                    else
                    {
                        model.vmBOM.Common_RawCategoryFK = RawCategoryId;
                        model.vmBOM.Merchandising_StyleFK = StyleId;
                        model.vmBOM.RawCategory = _service.GetBOMCategoryName(RawCategoryId);
                        model.ActionId = 1;
                    }
                    model.vmBOM.TypeID = TypeID;
                    model.vmBOM.TotalPiece = TotalPeice;
                    return View(model);

                case 2:
                    if (ID != 0)
                    {
                        
                        model.vmBOM = _service.BOMItemGetByID(ID);
                        model.ActionId = 2;
                    }
                    else
                    {
                        model.vmBOM.Common_RawCategoryFK = RawCategoryId;
                        model.vmBOM.Merchandising_StyleFK = StyleId;
                        model.ActionId = 1;
                    }
                    model.vmBOM.TypeID = TypeID;
                    model.vmBOM.TotalPiece = TotalPeice;
                    return View("FabricItemUI", model);
                case 3:
                    if (ID != 0)
                    {
                        model.ActionId = 2;
                        model.vmBOM = _service.BOMItemGetByID(ID);
                    }
                    else
                    {
                        model.vmBOM.Common_RawCategoryFK = RawCategoryId;
                        model.vmBOM.Merchandising_StyleFK = StyleId;
                        model.ActionId = 1;
                    }
                    model.vmBOM.TypeID = TypeID;
                    model.vmBOM.TotalPiece = TotalPeice;
                    model.vmBOM.RequiredQty = 1;
                    return View("ChargeItemUI", model);
                case 4:
                    if (ID != 0)
                    {
                        model.ActionId = 2;
                        model.vmBOM = _service.BOMItemGetByID(ID);
                    }
                    else
                    {
                        model.vmBOM.Common_RawCategoryFK = RawCategoryId;
                        model.vmBOM.Merchandising_StyleFK = StyleId;
                        model.ActionId = 1;
                    }
                    model.vmBOM.TypeID = TypeID;
                    model.vmBOM.TotalPiece = TotalPeice;
                    model.vmBOM.RequiredQty = 1;
                    return View("AccessoriesItemUI", model);
                default:
                    return View(model);
            }
        }
    }
}

Erp.App/Components/CBSItemUIViewComponent.cs
using Erp.Core.Services.Merchandising;
using Erp.Infrastructure;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Erp.App.Components
{
    public class CBSItemUIViewComponent : ViewComponent
    {
        private readonly MerchandisingService _service;
        public CBSItemUIViewComponent(InfrastructureDbContext db, IHttpContextAccessor httpContextAccessor)
        {
            _service = new MerchandisingService(db, httpContextAccessor.HttpContext);
        }

        public IViewComponentResult Invoke(int ID, int RawCategoryId, int CBSId,int TotalPeice,int TypeID)
        {
            ViewBag.SubCategoryList = new SelectList(_service.DDLRawCategoryItemByCatID(RawCategoryId), "Value", "Text");
            ViewBag.CurrencyList = new SelectList(_service.CurrencyDropDownList(), "Value", "Text");
            var model = new VMStyleView();
            model.vmCBSSlave = new VMCBSSlave();
            switch (TypeID)
            {
                case 1:
                    if (ID != 0)
                    {
                        model.ActionId = 2;
                        model.vmCBSSlave = _service.CBSItemGetByID(ID);
                    }
                    else
                    {
                        model.vmCBSSlave.Common_RawCategoryFK = RawCategoryId;
                        model.vmCBSSlave.Merchandising_CBSFK = CBSId;
                        model.ActionId = 1;
                    }
                    model.vmCBSSlave.TotalPieceQty = TotalPeice;
                    model.vmCBSSlave.TypeID = TypeID;
                    return View(model);
                case 2:
                    ViewBag.ColorList = new SelectList(_service.ColorDropDownList(), "Value", "Text");
                    if (ID != 0)
                    {
                        model.ActionId = 2;
                        model.vmCBSSlave = _service.CBSItemGetByID(ID);
                    }
                    else
                    {
                        model.vmCBSSlave.Common_RawCategoryFK = RawCategoryId;
                        model.vmCBSSlave.Merchandising_CBSFK = CBSId;
                        model.ActionId = 1;
                    }
                    model.vmCBSSlave.TotalPieceQty = TotalPeice;
                    model.vmCBSSlave.TypeID = TypeID;
                    return View("CBSFabricItemUI", model);
                case 3:
                    if (ID != 0)
                    {
                        model.ActionId = 2;
                        model.vmCBSSlave = _service.CBSItemGetByID(ID);
                    }
                    else
                    {
                        model.vmCBSSlave.Common_RawCategoryFK = RawCategoryId;
                        model.vmCBSSlave.Merchandising_CBSFK = CBSId;
                        model.ActionId = 1;
                    }
                    model.vmCBSSlave.TotalPieceQty = TotalPeice;
                    model.vmCBSSlave.RequiredQty = 1;
                    model.vmCBSSlave.TypeID = TypeID;
                    return View("CBSChargeItemUI", model);
                default:return View();
            }
        }
    }
}

Erp.App/Components/CBSUIViewComponent.cs
using Erp.Core.Services.Merchandising;
using Erp.Infrastructure;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Erp.App.Components
{
    public class CBSUIViewComponent : ViewComponent
    {
        private readonly MerchandisingService _service;
        public CBSUIViewComponent(InfrastructureDbContext db, IHttpContextAccessor httpContextAccessor)
        {
            _service = new MerchandisingService(db, httpContextAccessor.HttpContext);
        }

        public IViewComponentResult Invoke(int ID)
        {
            ViewBag.StyleList = new SelectList(_service.CBSStyleDownList(), "Value", "Text");
            ViewBag.BuyerList = new SelectList(_service.BuyerDropDownList(), "Value", "Text");
            var model = new VMCBS();
            if (ID != 0)
            {
                model = _service.CBSGetByID(ID);
            }
            return View(model);
        }
    }
}

Erp.App/Components/CommonUIViewComponent.cs
using Erp.Core.Services;
using Erp.Core.Services.Merchandising;
using Erp.Infrastructure;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace Erp.App.Components
{
    public class CommonUIViewComponent : ViewComponent
    {
        private readonly MerchandisingService _service;
        public CommonUIViewComponent(InfrastructureDbContext db, IHttpContextAccessor httpContextAccessor)
        {
            _service = new MerchandisingService(db, httpContextAccessor.HttpContext);
        }

        public IViewComponentResult Invoke(int id,int oid, string name)
        {
            if (name.Equals("Order"))
            {
                ViewBag.AgentList = new SelectList(_service.DDLAgentList(), "Value", "Text");
                ViewBag.AgentInspectionList = new SelectList(_service.DDLAgentInspection(), "Value", "Text");
                ViewBag.BuyerList = new SelectList(_service.BuyerDropDownList(), "Value", "Text");
                var model = new VMOrder();

                if (id != 0)
                {
                    model = _service.OrderById(id);
                }
                else
                {
                    model.ActionId = (int)ActionEnum.Add;
                    model.OrderDate = DateTime.Today;
                }

                return View("OrderFrom",model);
            }
            else if (name.Equals("Style"))
            {
                ViewBag.CurrencyList = new SelectList(_service.CurrencyDropDownList(), "Value", "Text");
                ViewBag.UnitList = new SelectList(_service.UnitDropDownList(), "Value", "Text");
                
                var model = new VMOrderView();
                model.vmStyle = new VMStyle();
                if (id != 0)
                {
                    model.vmStyle = _service.StyleById(id);
                    model.ActionId = (int)ActionEnum.Edit;
                    ViewBag.OrderSubCategoryList = new SelectList(_service.OrderSubCategoryByItemIDDropDownList(model.vmStyle.Mkt_ItemFK), "Value", "Text");
                    ViewBag.OrderItemList = new SelectList(_service.OrderItemByItemIDDropDownList(model.vmStyle.Mkt_ItemFK), "Value", "Text");
                }
                else
                {
                    ViewBag.OrderCategoryList = new SelectList(_service.OrderCategoryDropDownList(), "Value", "Text");
                    ViewBag.OrderSubCategoryList = new SelectList(_service.OrderSubCategoryDropDownList(), "Value", "Text");
                    ViewBag.OrderItemList = new SelectList(_service.OrderItemDropDownList(), "Value", "Text");

                    MultiSelectList lstColor = new MultiSelectList(_service.ColorDropDownList(), "Value", "Text");
                    MultiSelectList lstSize = new MultiSelectList(_service.SizeDropDownList(), "Value", "Text");
                    
                    model.ActionId = (int)ActionEnum.Add;
                    model.vmStyle.Merchandising_BuyerOrderFK = oid;
                    model.vmStyle.SizeList = lstSize;
                    model.vmStyle.ColorList = lstColor;
                }
                return View("StyleFrom",model);
            }
            else
            {
                return View();
            }
        }
    }
}

Erp.App/Components/DashboardUIViewComponent.cs
using Erp.Infrastructure;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Erp.Core.Services;
using Erp.Core.Services.Dashboard;
using Erp.Core.Services.Home;

namespace Erp.App.Components
{
    public class DashboardUIViewComponent: ViewComponent
    {
        private readonly DashboardService _service;
        private readonly VMLogin _vMLogin;
        private readonly int _UserID;
        public DashboardUIViewComponent(InfrastructureDbContext db, IHttpContextAccessor httpContextAccessor)
        {
            _vMLogin = httpContextAccessor.HttpContext.Session.GetObjectFromJson<VMLogin>("LoginUser");
            _service = new DashboardService(db, httpContextAccessor.HttpContext);
        }
        public IViewComponentResult Invoke()
        {
            var model = _service.GetAllDashboardData();
            
            return View("MerchandisingView",model);
        }
    }
}

Erp.App/Views/Shared/Components/BOMCategoryUI/BOMAccessoriesUI.cshtml
@model Erp.Core.Services.Merchandising.VMStyleView

<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="box box-info">
            <div class="box-header custom bg-info">
                <h4>
                    BOM Category : @Model.vmBOM.RawCategory
                </h4>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div id="BomItemUpdate_@Model.vmBOM.Common_RawCategoryFK"></div>
                <div id="BomItemCreate_@Model.vmBOM.Common_RawCategoryFK">
                    @await Component.InvokeAsync("BOMItemUI", new { ID = 0, RawCategoryId = Model.vmBOM.Common_RawCategoryFK, StyleId = Model.vmBOM.Merchandising_StyleFK, TotalPeice = Model.vmBOM.TotalPiece, TypeID = 4 })
                </div>
                <!--Body Will by Start Here-->
                <div class="table-responsive">
                    <table class="table table-striped table-hover text-nowrap">
                        <thead>
                            <tr class="bg-success">
                                <th>SL</th>
                                <th>Sub-Category</th>
                                <th>Raw Item</th>
                                <th>Color</th>
                                <th>Size</th>
                                <th>Consumption (Per Dz)</th>
                                <th>Consumption Qty</th>
                                <th>Required Qty</th>
                                <th>Tolerance (%)</th>
                                <th>Item Cost (Per Unit)</th>
                                <th>Total Cost</th>
                                <th>Description</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        @{int sl = 0;
                        }
                        <tbody class="bg-cyan">
                            @foreach (var item in Model.vmBOM.DataList)
                            {
                            <tr>
                                <td>@(++sl).</td>
                                <td>@item.RawSubCategory</td>
                                <td>@item.RawItem</td>
                                <td>@item.Color</td>
                                <td>@item.Size</td>
                                <td>@item.Consumption</td>
                                <td>@item.ConRequiredQty</td>
                                <td>@item.RequiredQty @item.UnitName</td>
                                <td>@item.Tolerance</td>
                                <td>@item.Currency @item.UnitPrice</td>
                                <td>@item.Currency @item.TotalPrice</td>
                                <td>@item.Description</td>
                                <td>
                                    @if (item.IsLocked)
                                    {
                                        <a onclick="makeUnApproved(@item.ID,@item.Merchandising_StyleFK);" class="linkPointer" data-toggle="modal" data-target="#unApprovedModal" title="Unapproved" data-placement="top"><i class="fa fa-lock" aria-hidden="true"></i></a>
                                    }
                                    else
                                    {
                                        <a data-modal="@Model.vmBOM.Common_RawCategoryFK" class="linkPointer" asp-action="BOMForm" asp-controller="Merchandising" asp-route-Id="@item.ID" asp-route-RawCatId="@item.Common_RawCategoryFK" asp-route-StyleId="@item.Merchandising_StyleFK" asp-route-TotalPeice="@Model.vmBOM.TotalPiece" asp-route-typeID="4"><i class="glyphicon glyphicon-pencil" aria-hidden="true"></i></a>
                                        <a onclick="deleteItemInfo(@item.ID,@item.Merchandising_StyleFK);" class="linkPointer" data-toggle="modal" data-target="#deleteModal" title="Delete" data-placement="top"><i class="glyphicon glyphicon-trash" aria-hidden="true"></i></a>
                                        <a onclick="makeApproved(@item.ID,@item.Merchandising_StyleFK);" class="linkPointer" data-toggle="modal" data-target="#approvedModal" title="Approved" data-placement="top"><i class="fa fa-unlock" aria-hidden="true"></i></a>
                                    }
                                </td>
                            </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <th colspan="4">.</th>
                                <th></th>
                                <th>Total Quantity</th>
                                @if (@Model.vmBOM.RequiredQty > 0)
                                {
                                    <th><span class="label label-primary">@Model.vmBOM.RequiredQty</span></th>
                                }
                                else
                                {
                                    <th><span class="label label-success">@Model.vmBOM.RequiredQty</span></th>
                                }
                                <th>.</th>
                                <th>Total Cost</th>
                                @if (@Model.vmBOM.RequiredQty > 0)
                                {
                                    <th><span class="label label-primary">@Model.vmBOM.TotalPrice</span></th>
                                }
                                else
                                {
                                    <th><span class="label label-success">@Model.vmBOM.TotalPrice</span></th>
                                }
                                <th>.</th>
                                <th>.</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

Erp.App/Views/Shared/Components/BOMCategoryUI/BOMChargeUI.cshtml
@model Erp.Core.Services.Merchandising.VMStyleView

<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="box box-info">
            <div class="box-header custom bg-info">
                <h4>
                    BOM Category : @Model.vmBOM.RawCategory
                </h4>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div id="BomItemUpdate_@Model.vmBOM.Common_RawCategoryFK"></div>
                <div id="BomItemCreate_@Model.vmBOM.Common_RawCategoryFK">
                    @await Component.InvokeAsync("BOMItemUI", new { ID = 0, RawCategoryId = Model.vmBOM.Common_RawCategoryFK, StyleId = Model.vmBOM.Merchandising_StyleFK, TotalPeice = Model.vmBOM.TotalPiece,TypeID=3 })
                </div>
                <!--Body Will by Start Here-->
                <div class="table-responsive">
                    <table class="table table-striped table-hover text-nowrap">
                        <thead>
                            <tr class="bg-success">
                                <th>SL</th>
                                <th>Charge Sub-Category</th>
                                <th>Charge Item</th>
                                <th>Total Cost</th>
                                <th>Description</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        @{int sl = 0;
                        }
                        <tbody class="bg-cyan">
                            @foreach (var item in Model.vmBOM.DataList)
                            {
                            <tr>
                                <td>@(++sl).</td>
                                <td>@item.RawSubCategory</td>
                                <td>@item.RawItem</td>
                                <td>@item.Currency @item.TotalPrice</td>
                                <td>@item.Description</td>
                                <td>
                                    @if (item.IsLocked)
                                    {
                                        <a onclick="makeUnApproved(@item.ID,@item.Merchandising_StyleFK);" class="linkPointer" data-toggle="modal" data-target="#unApprovedModal" title="Unapproved" data-placement="top"><i class="fa fa-lock" aria-hidden="true"></i></a>
                                    }
                                    else
                                    {
                                        <a data-modal="@Model.vmBOM.Common_RawCategoryFK" class="linkPointer" asp-action="BOMForm" asp-controller="Merchandising" asp-route-Id="@item.ID" asp-route-RawCatId="@item.Common_RawCategoryFK" asp-route-StyleId="@item.Merchandising_StyleFK" asp-route-TotalPeice="@Model.vmBOM.TotalPiece" asp-route-typeID="3"><i class="glyphicon glyphicon-pencil" aria-hidden="true"></i></a>
                                        <a onclick="deleteItemInfo(@item.ID,@item.Merchandising_StyleFK);" class="linkPointer" data-toggle="modal" data-target="#deleteModal" title="Delete" data-placement="top"><i class="glyphicon glyphicon-trash" aria-hidden="true"></i></a>
                                        <a onclick="makeApproved(@item.ID,@item.Merchandising_StyleFK);" class="linkPointer" data-toggle="modal" data-target="#approvedModal" title="Approved" data-placement="top"><i class="fa fa-unlock" aria-hidden="true"></i></a>
                                    }

                                </td>
                            </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <th colspan="2">.</th>
                                <th>Total Cost</th>
                                @if (Model.vmBOM.TotalPrice > 0)
                                {
                                    <th><span class="label label-primary">@Model.vmBOM.TotalPrice</span></th>
                                }
                                else
                                {
                                    <th><span class="label label-success">@Model.vmBOM.TotalPrice</span></th>
                                }
                                <th>.</th>
                                <th>.</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>