Erp.App/Controllers/InventoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Erp.Core.Services.Inventory;
using Microsoft.Extensions.Logging;
using Erp.Infrastructure;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;
using Erp.Core.Services;
using Microsoft.AspNetCore.Http;
using Erp.Core.Services.User;
using Erp.Core.Services.Procurement;
using Erp.Core.Services.Integration;

namespace Erp.App.Controllers
{
    [SoftwareAdmin]
    public class InventoryController : Controller
    {
        const string SessionController = "ControllerName";
        const string SessionAction = "ActionName";
        const string SessionName = "LoginName";
        const string SessionId = "LoginId";
        private readonly ILogger _logger;
        private readonly InventoryService _service;
        private readonly IntegrationService _integrationService;
        public InventoryController(InfrastructureDbContext db, ILogger<InventoryController> logger, IHttpContextAccessor httpContextAccessor)
        {
            _integrationService = new IntegrationService(db, httpContextAccessor.HttpContext);
            _service = new InventoryService(db);
            SessionHandler sessionHandler = new SessionHandler(db, httpContextAccessor.HttpContext);
            sessionHandler.Adjust();
            _logger = logger;
        }

        #region Inventory Report
        public async Task<IActionResult> InventoryIndex()
        {
            ViewBag.RawCategoryList = new SelectList(_integrationService.RawCategoryDropDownList(), "Value", "Text");
            ViewBag.RawSubCategoryList = new SelectList(_integrationService.RawSubCategoryDropDownList(), "Value", "Text");
            ViewBag.RawItemList = new SelectList(_integrationService.RawItemDropDownList(), "Value", "Text");
            var fromdt = DateTime.Now.AddDays(-7);
            var todt = DateTime.Now;
            int id = 0;
            int storeTypeFk = 1;
            var model = await Task.Run(() => _service.RawInventorySummeryListGet(fromdt,todt, id, storeTypeFk));
            _logger.LogInformation("--From: " + ControllerContext.ActionDescriptor.ActionName + "InventoryListGet(),  Get Last Sevendays Inventory.");
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> InventoryIndex(VmInventory model)
        {
            ViewBag.RawCategoryList = new SelectList(_integrationService.RawCategoryDropDownList(), "Value", "Text");
            ViewBag.RawSubCategoryList = new SelectList(_integrationService.RawSubCategoryDropDownList(), "Value", "Text");
            ViewBag.RawItemList = new SelectList(_integrationService.RawItemDropDownList(), "Value", "Text");
            int storeTypeFk = 1;
            var data = await Task.Run(() => _service.RawInventorySummeryListGet(model.FromDate, model.ToDate, model.Common_RawItemFK, storeTypeFk));
            _logger.LogInformation("--From: " + ControllerContext.ActionDescriptor.ActionName + "InventoryListGet(),  Get Inventory Summery List as per date range and id wise.");
            return View(data);
        }

        public async Task<IActionResult> ItemWiseInventoryDetatils(int id=0,int storeTypeFk=0)
        {
             var model = await Task.Run(() => _service.RawInventoryItemWiseListGet(id, storeTypeFk));
            _logger.LogInformation("--From: " + ControllerContext.ActionDescriptor.ActionName + "InventoryListGet(),  Get Last Sevendays Inventory.");
            return View(model);
        }

        public JsonResult RawSubCategoryDropDownSpecific(int id)
        {
            if (id != 0)
            {
                var list = _integrationService.RawSubCategoryDropDowncascading(id);
                return Json(list);
            }
            return null;
        }

        public JsonResult RawItemDropDownSpecific(int id)
        {
            if (id != 0)
            {
                var list = _integrationService.RawItemDropDownListSpecific(id);
                return Json(list);
            }
            return null;
        }


        public async Task<IActionResult> WipInventoryIndex()
        {
            ViewBag.RawCategoryList = new SelectList(_integrationService.RawCategoryDropDownList(), "Value", "Text");
            ViewBag.RawSubCategoryList = new SelectList(_integrationService.RawSubCategoryDropDownList(), "Value", "Text");
            ViewBag.RawItemList = new SelectList(_integrationService.RawItemDropDownList(), "Value", "Text");
            var fromdt = DateTime.Now.AddDays(-7);
            var todt = DateTime.Now;
            int id = 0;
            int storeTypeFk = 2;
            var model = await Task.Run(() => _service.RawInventorySummeryListGet(fromdt, todt, id, storeTypeFk));
            _logger.LogInformation("--From: " + ControllerContext.ActionDescriptor.ActionName + "InventoryListGet(),  Get Last Sevendays Inventory.");
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> WipInventoryIndex(VmInventory model)
        {
            ViewBag.RawCategoryList = new SelectList(_integrationService.RawCategoryDropDownList(), "Value", "Text");
            ViewBag.RawSubCategoryList = new SelectList(_integrationService.RawSubCategoryDropDownList(), "Value", "Text");
            ViewBag.RawItemList = new SelectList(_integrationService.RawItemDropDownList(), "Value", "Text");
            int storeTypeFk = 2;
            var data = await Task.Run(() => _service.RawInventorySummeryListGet(model.FromDate, model.ToDate, model.Common_RawItemFK, storeTypeFk));
            _logger.LogInformation("--From: " + ControllerContext.ActionDescriptor.ActionName + "InventoryListGet(),  Get Inventory Summery List as per date range and id wise.");
            return View(data);
        }


        public async Task<IActionResult> FinishInventoryIndex()
        {
            ViewBag.FinishCategoryList = new SelectList(_integrationService.FinishCategoryDropDownList(), "Value", "Text");
            ViewBag.FinishSubCategoryList = new SelectList(_integrationService.FinishSubCategoryDropDownList(), "Value", "Text");
            ViewBag.FinishItemList = new SelectList(_integrationService.FinishItemDropDownList(), "Value", "Text");
            var fromdt = DateTime.Now.AddDays(-7);
            var todt = DateTime.Now;
            int id = 0;
            int storeTypeFk = 3;
            var model = await Task.Run(() => _service.FinishInventorySummeryListGet(fromdt, todt, id, storeTypeFk));
            _logger.LogInformation("--From: " + ControllerContext.ActionDescriptor.ActionName + "InventoryListGet(),  Get Last Sevendays Inventory.");
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> FinishInventoryIndex(VmInventory model)
        {
            ViewBag.FinishCategoryList = new SelectList(_integrationService.FinishCategoryDropDownList(), "Value", "Text");
            ViewBag.FinishSubCategoryList = new SelectList(_integrationService.FinishSubCategoryDropDownList(), "Value", "Text");
            ViewBag.FinishItemList = new SelectList(_integrationService.FinishItemDropDownList(), "Value", "Text");
            int storeTypeFk = 3;
            var data = await Task.Run(() => _service.FinishInventorySummeryListGet(model.FromDate, model.ToDate, model.Common_RawItemFK, storeTypeFk));
            _logger.LogInformation("--From: " + ControllerContext.ActionDescriptor.ActionName + "InventoryListGet(),  Get Inventory Summery List as per date range and id wise.");
            return View(data);
        }
        public async Task<IActionResult> ItemWiseFinishInventoryDetatils(int id = 0, int storeTypeFk = 0)
        {
            var model = await Task.Run(() => _service.FinishInventoryItemWiseListGet(id, storeTypeFk));
            _logger.LogInformation("--From: " + ControllerContext.ActionDescriptor.ActionName + "InventoryListGet(),  Get Last Sevendays Inventory.");
            return View(model);
        }

        public JsonResult FinishSubCategoryDropDownSpecific(int id)
        {
            if (id != 0)
            {
                var list = _integrationService.FinishSubCategoryDropDownCascading(id);
                return Json(list);
            }
            return null;
        }

        public JsonResult FinishItemDropDownSpecific(int id)
        {
            if (id != 0)
            {
                var list = _integrationService.FinishItemDropDownListCascading(id);
                return Json(list);
            }
            return null;
        }

        //RawItemDropDownListSpecific
        #endregion
    }
}

Erp.App/Views/Inventory/FinishInventoryIndex.cshtml
@model Erp.Core.Services.Inventory.VmInventory
@{
    ViewData["Title"] = "Finish Inventory List";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var tdId = "tdId";
    var tdtitle = "tdtitle";
    var tddescription = "tddescription";
    var tddate = "tddate";
}
@using (Html.BeginForm("FinishInventoryIndex", "InventoryController", FormMethod.Post, new { id = "FinishInventoryIndex", @class = "formValidator" }))
{
    <section class="col-lg-12 col-md-12 col-sm-12">
        <div class="row">
            <div class="box">
                <div class="box-danger">
                    <div class="box-header">
                        <h3>
                            Finish Inventory:
                            &nbsp;&nbsp;
                        </h3>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="ddLStore" class="col-form-label">Category Name:</label>
                                    @Html.DropDownListFor(model => model.CategoryFK, ViewBag.FinishCategoryList as SelectList, new { id = "ddlCategoryFK", @class = "searchingDropdown form-control ddlReset", style = "width:100%", required = "required" })
                                    @Html.ValidationMessageFor(model => model.CategoryFK, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="ddLStore" class="col-form-label">Sub Category Name:</label>
                                    @Html.DropDownListFor(model => model.SubCategoryFK, ViewBag.FinishSubCategoryList as SelectList, new { id = "ddlSubCategoryFK", @class = "searchingDropdown form-control ddlReset", style = "width:100%", required = "required" })
                                    @Html.ValidationMessageFor(model => model.SubCategoryFK, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="ddLStore" class="col-form-label">Item Name:</label>
                                    @Html.DropDownListFor(model => model.Common_RawItemFK, ViewBag.FinishItemList as SelectList, new { id = "ddlItemFK", @class = "searchingDropdown form-control ddlReset", style = "width:100%", required = "required" })
                                    @Html.ValidationMessageFor(model => model.Common_RawItemFK, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group col-md-4">
                                <label for="txtOrderDate" class="col-form-label">From Date:</label>
                                <div class="input-group date">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    <input name="FromDate" type="text" class="form-control pull-right datePicker1" id="FromDate" autocomplete="off" placeholder="From Date" required>
                                    @Html.ValidationMessageFor(model => model.FromDate, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="txtOrderDate" class="col-form-label">To Date:</label>
                                <div class="input-group date">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    <input name="ToDate" type="text" class="form-control pull-right datePicker1" id="ToDate" autocomplete="off" placeholder="To Date" required>
                                    @Html.ValidationMessageFor(model => model.ToDate, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="txtOrderDate" class="col-form-label"></label>
                                <div class="input-group" style="text-align:right">
                                    <button type="submit" id="btnSearch" class="btn btn-primary"><i class="fa fa-search"></i> Search</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <!--Body Will by Start Here-->
                        <div class="table-responsive">
                            <table id="tableX" class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>SL</th>
                                        <th class="hidden"></th>
                                        <th>Item Name</th>
                                        <th>Inventory Type</th>
                                        @*<th>Transaction Type</th>*@
                                        <th>Quantity</th>
                                        <th>Unit Value</th>
                                        <th>Total Value</th>
                                        @*<th>Transaction Date</th>*@
                                    </tr>
                                </thead>
                                @{int sl = 0;
                                }
                                <tbody>

                                    @foreach (var item in Model.DataList)
                                    {
                                        <tr>
                                            <td>@(++sl)</td>
                                            <td id="@tdId@item.ID" class="hidden">
                                                @item.ID
                                                <input type="hidden" id="Common_RawItemFK_@item.ID" value="@item.Common_RawItemFK" />
                                            </td>
                                            <td>
                                                <a asp-action="ItemWiseFinishInventoryDetatils" asp-controller="Inventory" asp-route-id="@item.Common_RawItemFK" asp-route-storeTypeFk="3" title="Details" target="_blank"><label class="col-form-label" style="cursor:pointer;">@item.ItemName</label></a>
                                            </td>
                                            <td id="@tdtitle@item.ID">
                                                @if (item.StoreTypeFk == 1)
                                                {
                                                    <span class="label label-success">RAW</span>
                                                }
                                                else if (item.StoreTypeFk == 2)
                                                {
                                                    <span class="label label-success">WIP</span>
                                                }
                                                else if (item.StoreTypeFk == 3)
                                                {
                                                    <span class="label label-success">FINISH</span>
                                                }
                                            </td>
                                            @*<td id="@tddescription@item.ID">@item.TransactionType</td>*@
                                            <td id="@tddescription@item.ID">
                                                @*<div class="input-group-addon">*@
                                                <label>@item.Amount</label>
                                                <span>@item.UnitName</span>
                                                @*</div>*@
                                            <td id="@tddescription@item.ID">@item.Price</td>
                                            <td id="@tddescription@item.ID">
                                                @String.Format("{0:0,0.00}", item.TotalPrice)
                                            </td>
                                            @*<td id="@tddate@item.ID">@item.Time.ToString("yyyy-MM-dd")</td>*@
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <div class="box-footer">

                    </div>
                </div>
            </div>
        </div>
    </section>
}

@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('.formValidator').bootstrapValidator();
             $(".datePicker1").datepicker('setStartDate', '@System.DateTime.Now.ToString("yyyy-MM-dd")');
        });
        $('.searchingDropdown').select2();
        $("#ddlCategoryFK").change(function () {
            var Id = $("#ddlCategoryFK").val();
            if (Id != "") {
                //$("#ddlSubCategoryFK").empty();
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("FinishSubCategoryDropDownSpecific")",
                    datatype: "Json",
                    data: { id: Id  },
                    success: function (data) {
                        var items = "";
                        items += "<option value ='' selected>Please Select</option>";
                        $.each(data, function (Index,value) {
                            items += ('<option value="' + value.value + '">' + value.text  + '</option>');
                        });
                        $("#ddlSubCategoryFK").html(items);
                    }
                });
            }
        });

        $("#ddlSubCategoryFK").change(function () {
            var Id = $("#ddlSubCategoryFK").val();
            if (Id != "") {
                //$("#ddlSubCategoryFK").empty();
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("FinishItemDropDownSpecific")",
                    datatype: "Json",
                    data: { id: Id  },
                    success: function (data) {
                        var items = "";
                        items += "<option value ='' selected>Please Select</option>";
                        $.each(data, function (Index,value) {
                            items += ('<option value="' + value.value + '">' + value.text  + '</option>');
                        });
                        $("#ddlItemFK").html(items);
                    }
                });
            }
        });

    </script>
}

Erp.App/Views/Inventory/InventoryIndex.cshtml
@model Erp.Core.Services.Inventory.VmInventory
@{
    ViewData["Title"] = "Inventory List";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var tdId = "tdId";
    var tdtitle = "tdtitle";
    var tddescription = "tddescription";
    var tddate = "tddate";
}
@using (Html.BeginForm("InventoryIndex", "InventoryController", FormMethod.Post, new { id = "InventoryIndex", @class = "formValidator" }))
{
    <section class="col-lg-12 col-md-12 col-sm-12">
        <div class="row">
            <div class="box">
                <div class="box-danger">
                    <div class="box-header">
                        <h3>
                            RAW Inventory:
                            &nbsp;&nbsp;
                        </h3>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="ddLStore" class="col-form-label">Category Name:</label>
                                    @Html.DropDownListFor(model => model.CategoryFK, ViewBag.RawCategoryList as SelectList, new { id = "ddlCategoryFK", @class = "searchingDropdown form-control ddlReset", style = "width:100%", required = "required" })
                                    @Html.ValidationMessageFor(model => model.CategoryFK, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="ddLStore" class="col-form-label">Sub Category Name:</label>
                                    @Html.DropDownListFor(model => model.SubCategoryFK, ViewBag.RawSubCategoryList as SelectList, new { id = "ddlSubCategoryFK", @class = "searchingDropdown form-control ddlReset", style = "width:100%", required = "required" })
                                    @Html.ValidationMessageFor(model => model.SubCategoryFK, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="ddLStore" class="col-form-label">Item Name:</label>
                                    @Html.DropDownListFor(model => model.Common_RawItemFK, ViewBag.RawItemList as SelectList, new { id = "ddlItemFK", @class = "searchingDropdown form-control ddlReset", style = "width:100%", required = "required" })
                                    @Html.ValidationMessageFor(model => model.Common_RawItemFK, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group col-md-4">
                                <label for="txtOrderDate" class="col-form-label">From Date:</label>
                                <div class="input-group date">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    <input name="FromDate" type="text" class="form-control pull-right datePicker1" id="FromDate" autocomplete="off" placeholder="From Date" required>
                                    @Html.ValidationMessageFor(model => model.FromDate, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="txtOrderDate" class="col-form-label">To Date:</label>
                                <div class="input-group date">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    <input name="ToDate" type="text" class="form-control pull-right datePicker1" id="ToDate" autocomplete="off" placeholder="To Date" required>
                                    @Html.ValidationMessageFor(model => model.ToDate, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="txtOrderDate" class="col-form-label"></label>
                                <div class="input-group" style="text-align:right">
                                    <button type="submit" id="btnSearch" class="btn btn-primary"><i class="fa fa-search"></i> Search</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <!--Body Will by Start Here-->
                        <div class="table-responsive">
                            <table id="tableX" class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>SL</th>
                                        <th class="hidden"></th>
                                        <th>Item Name</th>
                                        <th>Inventory Type</th>
                                        @*<th>Transaction Type</th>*@
                                        <th>Quantity</th>
                                        <th>Unit Value</th>
                                        <th>Total Value</th>
                                        @*<th>Transaction Date</th>*@
                                    </tr>
                                </thead>
                                @{int sl = 0;
                                }
                                <tbody>

                                    @foreach (var item in Model.DataList)
                                    {
                                        <tr>
                                            <td>@(++sl)</td>
                                            <td id="@tdId@item.ID" class="hidden">
                                                @item.ID
                                                <input type="hidden" id="Common_RawItemFK_@item.ID" value="@item.Common_RawItemFK" />
                                            </td>
                                            <td>
                                                <a asp-action="ItemWiseInventoryDetatils" asp-controller="Inventory" asp-route-id="@item.Common_RawItemFK" asp-route-storeTypeFk="1" title="Details"  target="_blank"><label class="col-form-label" style="cursor:pointer;">@item.ItemName</label></a>
                                            </td>
                                            <td id="@tdtitle@item.ID">
                                                @if (item.StoreTypeFk == 1)
                                                {
                                                    <span class="label label-success">RAW</span>
                                                }
                                                else if (item.StoreTypeFk == 2)
                                                {
                                                    <span class="label label-success">WIP</span>
                                                }
                                                else if (item.StoreTypeFk == 3)
                                                {
                                                    <span class="label label-success">FINISH</span>
                                                }
                                            </td>
                                            @*<td id="@tddescription@item.ID">@item.TransactionType</td>*@
                                            <td id="@tddescription@item.ID">
                                                @*<div class="input-group-addon">*@
                                                <label>@item.Amount</label>
                                                <span>@item.UnitName</span>
                                                @*</div>*@
                                            <td id="@tddescription@item.ID">@item.Price</td>
                                            <td id="@tddescription@item.ID">
                                                @String.Format("{0:0,0.00}", item.TotalPrice)
                                            </td>
                                            @*<td id="@tddate@item.ID">@item.Time.ToString("yyyy-MM-dd")</td>*@
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <div class="box-footer">

                    </div>
                </div>
            </div>
        </div>
    </section>
}

@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('.formValidator').bootstrapValidator();
             $(".datePicker1").datepicker('setStartDate', '@System.DateTime.Now.ToString("yyyy-MM-dd")');
        });
        $('.searchingDropdown').select2();
        $("#ddlCategoryFK").change(function () {
            var Id = $("#ddlCategoryFK").val();
            if (Id != "") {
                //$("#ddlSubCategoryFK").empty();
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("RawSubCategoryDropDownSpecific")",
                    datatype: "Json",
                    data: { id: Id  },
                    success: function (data) {
                        var items = "";
                        items += "<option value ='' selected>Please Select</option>";
                        $.each(data, function (Index,value) {
                            items += ('<option value="' + value.value + '">' + value.text  + '</option>');
                        });
                        $("#ddlSubCategoryFK").html(items);
                    }
                });
            }
        });

        $("#ddlSubCategoryFK").change(function () {
            var Id = $("#ddlSubCategoryFK").val();
            if (Id != "") {
                //$("#ddlSubCategoryFK").empty();
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("RawItemDropDownSpecific")",
                    datatype: "Json",
                    data: { id: Id  },
                    success: function (data) {
                        var items = "";
                        items += "<option value ='' selected>Please Select</option>";
                        $.each(data, function (Index,value) {
                            items += ('<option value="' + value.value + '">' + value.text  + '</option>');
                        });
                        $("#ddlItemFK").html(items);
                    }
                });
            }
        });
        
    </script>
}