Erp.App/Controllers/ProcurementController.cs
using Erp.Core.Services;
using Erp.Core.Services.Home;
using Erp.Core.Services.Procurement;
using Erp.Core.Services.User;
using Erp.Infrastructure;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace Erp.App.Controllers
{

    [SoftwareAdmin]
    public class ProcurementController : Controller
    {
        private readonly ILogger _logger;
        private readonly ProcurementService _service;
        private readonly HttpContext _httpContext;
        private readonly int _UserID;
        private readonly VMLogin _vMLogin;
        IDataProtector _protector;
        public ProcurementController(InfrastructureDbContext db, IHttpContextAccessor httpContextAccessor, ILogger<ProcurementController> logger, IDataProtectionProvider provider)
        {
            SessionHandler sessionHandler = new SessionHandler(db, httpContextAccessor.HttpContext);
            sessionHandler.Adjust();
            //_protector = provider.CreateProtector(GetType().FullName);
            _protector = provider.CreateProtector("OSS.ERP");
            _vMLogin = httpContextAccessor.HttpContext.Session.GetObjectFromJson<VMLogin>("LoginUser");
            _httpContext = httpContextAccessor.HttpContext;
            _UserID = _vMLogin.ID;
            _service = new ProcurementService(db, httpContextAccessor.HttpContext);
            _logger = logger;
        }

        #region Common
        public async Task<IActionResult> RawSubCategoryGet(int id)
        {
            if (id < 0) { return RedirectToAction("Error", "Home"); }

            var model = await Task.Run(() => _service.RawSubCategoryGet(id));



            var list = model.Select(x => new { Value = x.ID, Text = x.Name }).ToList();

            _logger.LogInformation("--From: " + ControllerContext.ActionDescriptor.ActionName + "RawSubCategoryGet(id), RawSubCategory Get by RawCategoryid).");
            return Json(list);
        }
        public async Task<IActionResult> RawItemGet(int id)
        {
            if (id < 0) { return RedirectToAction("Error", "Home"); }

            var model = await Task.Run(() => _service.RawItemGet(id));
            var list = model.Select(x => new { Value = x.ID, Text = x.Name }).ToList();

            _logger.LogInformation("--From: " + ControllerContext.ActionDescriptor.ActionName + "RawItemGet(id), RawItemGet Get by RawSubCategoryid).");
            return Json(list);
        }
        public async Task<IActionResult> RawItemInfoGet(int id)
        {
            if (id < 0) { return RedirectToAction("Error", "Home"); }

            var model = await Task.Run(() => _service.RawItemInfoGet(id));

            _logger.LogInformation("--From: " + ControllerContext.ActionDescriptor.ActionName + "RawItemInfoGet(id), RawItemInfo Get by RawItemid).");
            return Json(model);
        }
        #endregion

        #region Purchase_Requisition

        public async Task<IActionResult> CreatePR(int id = 0)
        {
            VMPurchaseRequisitionSlave model = new VMPurchaseRequisitionSlave();
            if (id == 0)
            {
                model = new VMPurchaseRequisitionSlave()
                {
                    Status = PRStatusEnum.Draft,

                    DataListSlave = new List<VMPurchaseRequisitionSlave>(),

                };
            }
            else if (id > 0)
            {
                model = await _service.PRWithSlaveListGet(new VMPurchaseRequisitionSlave() { Procurement_PurchaseRequisitionFK = id });

            }
            model.RawCategoryList = new SelectList(_service.RawCategoryDropDownList(), "Value", "Text");
            model.UserList = new SelectList(_service.UserDropDownList(), "Value", "Text");

            _logger.LogInformation("--From: " + ControllerContext.ActionDescriptor.ActionName + "PRWithSlaveListGet / RawCategoryDropDownList / EmployeeDropDownList, open Regular PR Create Page).");
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> CreatePR(VMPurchaseRequisitionSlave model)
        {
            #region session values
            string sUser = HttpContext.Session.GetString("User");
            string nUserId = HttpContext.Session.GetString("UserID");
            #endregion
            if (string.IsNullOrEmpty(sUser) || string.IsNullOrEmpty(nUserId)) { return RedirectToAction("Login", "Auth"); }
            model.User = sUser;
            model.UserID = int.Parse(nUserId);

            if (model.ActionEum == ActionEnum.Add)
            {
                if (model.Procurement_PurchaseRequisitionFK <= 0)
                {

                    model.Status = PRStatusEnum.Draft;

                    model.Procurement_PurchaseRequisitionFK = await _service.PurchaseRequisitionAdd(new VMPurchaseRequisition() { User = sUser, UserID = int.Parse(nUserId), Status = PRStatusEnum.Draft, PRType = PRTypeEnum.External, OriginType = ProcurementOriginTypeEnum.Regular });
                }

                //Add 
                await _service.PRSlaveAdd(model);
            }
            else if (model.ActionEum == ActionEnum.Edit)
            {
                //Edit
                await _service.PRSlaveEdit(model);
            }
            else if (model.ActionEum == ActionEnum.Delete)
            {
                //Delete
                await _service.PRSlaveDelete(model.ID);
            }
            else if ((int)model.ActionEum > 3 && model.Procurement_PurchaseRequisitionFK > 0)
            {
                //Delete
                await _service.PurchaseRequisitionStatusUpdate(new VMPurchaseRequisition() { User = sUser, ID = model.Procurement_PurchaseRequisitionFK, ActionId = (int)model.ActionEum, PRActionId = model.PRActionId, Description = model.Description });
            }
            else
            {
                _logger.LogInformation("--From: " + ControllerContext.ActionDescriptor.ActionName + " (PurchaseRequisitionAdd,PRSlaveAdd) / PRSlaveEdit / PRSlaveDelete / PurchaseRequisitionStatusUpdate, Regular PR Functionalities failed).");
                return RedirectToAction("Error", "Home");
            }
            _logger.LogInformation("--From: " + ControllerContext.ActionDescriptor.ActionName + " (PurchaseRequisitionAdd,PRSlaveAdd) / PRSlaveEdit / PRSlaveDelete / PurchaseRequisitionStatusUpdate, Regular PR Functionalities).");
            return RedirectToAction("CreatePR", new { id = model.Procurement_PurchaseRequisitionFK });
        }

        public async Task<IActionResult> MerchandisingPR(int id = 0, int id2 = 0)
        {
            VMPurchaseRequisitionSlave model = new VMPurchaseRequisitionSlave();
            if (id == 0)
            {
                model = new VMPurchaseRequisitionSlave()
                {
                    Status = PRStatusEnum.Draft,
                    DataListSlave = new List<VMPurchaseRequisitionSlave>()
                };
            }
            else if (id > 0)
            {
                model = await _service.PRWithSlaveListGet(new VMPurchaseRequisitionSlave() { Procurement_PurchaseRequisitionFK = id });

            }
            model.OriginType = (ProcurementOriginTypeEnum)id2;
            model.ApprovedBOMStyleList = new SelectList(_service.ApprovedStyleList(model.Procurement_PurchaseRequisitionFK), "Value", "Text");
            _logger.LogInformation("--From: " + ControllerContext.ActionDescriptor.ActionName + "PRWithSlaveListGet / ApprovedStyleList, open Merchandising PR Create Page).");
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> MerchandisingPR(VMPurchaseRequisitionSlave model)
        {
            #region session values
            string sUser = HttpContext.Session.GetString("User");
            string nUserId = HttpContext.Session.GetString("UserID");
            #endregion
            if (string.IsNullOrEmpty(sUser) || string.IsNullOrEmpty(nUserId)) { return RedirectToAction("Login", "Auth"); }
            model.User = sUser;
            model.UserID = int.Parse(nUserId);

            if (model.ActionEum == ActionEnum.Add)
            {
                if (model.Procurement_PurchaseRequisitionFK <= 0)
                {

                    model.Status = PRStatusEnum.Draft;

                    model.Procurement_PurchaseRequisitionFK = await _service.PurchaseRequisitionAdd(new VMPurchaseRequisition() { User = sUser, UserID = int.Parse(nUserId), Status = PRStatusEnum.Draft, PRType = PRTypeEnum.External, OriginType = ProcurementOriginTypeEnum.Merchandising });
                }

                //Add 
                await _service.PRSlaveAdd(model);
            }
            else if (model.ActionEum == ActionEnum.Edit)
            {
                //Edit
                await _service.PRSlaveEdit(model);
            }
            else if (model.ActionEum == ActionEnum.Delete)
            {
                //Delete
                await _service.PRSlaveDelete(model.ID);
            }
            else if ((int)model.ActionEum > 3 && model.Procurement_PurchaseRequisitionFK > 0)
            {
                //Delete
                await _service.PurchaseRequisitionStatusUpdate(new VMPurchaseRequisition() { User = sUser, ID = model.Procurement_PurchaseRequisitionFK, ActionId = (int)model.ActionEum, PRActionId = model.PRActionId, Description = model.Description });
            }
            else
            {
                _logger.LogInformation("--From: " + ControllerContext.ActionDescriptor.ActionName + " (PurchaseRequisitionAdd,PRSlaveAdd) / PRSlaveEdit / PRSlaveDelete / PurchaseRequisitionStatusUpdate, Merchandising PR Functionalities failed).");
                return RedirectToAction("Error", "Home");
            }

Erp.App/Views/Procurement/ProcurementPurchaseInvoice.cshtml
@{
    ViewData["Title"] = "Procurement Purchase Invoice";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var tdId = "tdId";
    var tdOrderId = "tdOrderId";
    var tdSupplierId = "tdSupplierId";
    var tdSupplierName = "tdSupplierName";
    var tdEmployeeId = "tdEmployeeId";
    var tdEmployeeName = "tdEmployeeName";
    var tdCurrencyId = "tdCurrencyId";
    var tdCurrencyName = "tdCurrencyName";
    var tdCreationDate = "tdCreationDate";
    var tdOrderDate = "tdOrderDate";
    var tdDescription = "tdDescription";
    var tdTAndC = "tdTAndC";
    var tdStatusName = "tdStatusName";
    var tdCreatedBy = "tdCreatedBy";


    //  var tdId = "tdId";
    var tdPOID = "tdPOID";
    var tdPurchasingPrice = "tdPurchasingPrice";
    var tdInspection = "tdInspection";
    var tdInspectionRequired = "tdInspectionRequired";
    var tdInspectionRequiredInPR = "tdInspectionRequiredInPR";
    var tdRawItemID = "tdRawItemID";
    var tdRawSubCategoryID = "tdRawSubCategoryID";
    var tdRawCategoryID = "tdRawCategoryID";
    var tdReqSlaveId = "tdReqSlaveId";
    var tdRawItemName = "tdRawItemName";
    var tdUnitName = "tdUnitName";
    var tdDescriptionSlave = "tdDescriptionSlave";
    var tdRequisitionQuantity = "tdRequisitionQuantity";
    var tdProcuredQuantity = "tdProcuredQuantity";
    var tdRestQuantity = "tdRestQuantity";
    var tdPurchaseQuantity = "tdPurchaseQuantity";
    var tdAvailableQuantity = "tdAvailableQuantity";
    var tdTotalPrice = "tdTotalPrice";


    var PIStatus = Model.AuthorizationStatus;
}
@model Erp.Core.Services.Procurement.VMPurchaseInvoiceSlave
@using (Html.BeginForm("ProcurementPurchaseInvoice", "Procurement", FormMethod.Post, new { id = "ProcurementPurchaseInvoice", @class = "formValidator", onreset = "resetDDL();" }))
{
    @Html.HiddenFor(model => model.ID, new { Value = "", id = "hdfId" })
    @Html.HiddenFor(model => model.ActionId, new { Value = "", id = "hdfActionId" })
    @Html.HiddenFor(model => model.InvoiceActionId, new { Value = "", id = "hdfPOActionId" })
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="box">

        <div class="box box-success">
            <div class="box-header custom bg-success">
                <h4>
                    Draft Invoice:
                </h4>
            </div>

            <div class="box-body">
                <div class="form-group">
                    <label for="ddlSupplier" class="col-form-label">PO List:</label>
                    @Html.DropDownListFor(model => model.POID, Model.ApprovedSInItemList as SelectList, "Please Select", new { id = "ddlApprovedPR", @class = "searchingDropdown form-control ddlReset", style = "width:100%", required = "required" })
                    @Html.ValidationMessageFor(model => model.POID, "", new { @class = "text-danger" })
                </div>
            </div>

        </div>
    </div>
}
@using (Html.BeginForm("PurchaseInvoiceSlaveListWithMaster", "Procurement", FormMethod.Post, new { id = "PurchaseInvoiceSlaveListWithMaster", @class = "formValidator", onreset = "resetDDL();" }))
{
    <div class="box-body">
        <div id="divPOSlaveList"></div>
    </div>
}



@section scripts {

    <script type="text/javascript">
        $(document).ready(function () {
            $('.formValidator').bootstrapValidator();
            @*$(".datePicker").datepicker('setDate','@System.DateTime.Now.ToString("yyyy-MM-dd")');*@
            $(".datePicker").datepicker('setStartDate', '@System.DateTime.Now.ToString("yyyy-MM-dd")');
        });

        function resetDDL() {

            $('#hidId').empty();
            $('#ActionId').val(1);
            $('#btnSave').html("<i class='fa fa-floppy-o'></i>&nbsp;Save");

            $('.ddlReset').val('').trigger('change');
            $('#PurchaseInvoice').bootstrapValidator("resetForm", true);

        }

        function menuinfo(elem) {
            if (elem !== null) {

                $.ajax({
                    type: "GET",
                    url: "/Procurement/PurchaseInvoiceSpecific?id=" + elem.id,
                    datatype: "Json",

                    success: function (data) {

                        if (data) {
                            $('#divEditPOInfo').html(data);

                            //$("#txtOrderDate").val($('#tdOrderDate' + elem.id).text().trim());

                            $('.formValidator').bootstrapValidator();
                            $('.datePicker').datepicker({
                                format: "yyyy-mm-dd",
                                // format: "d/m/yy",
                                autoclose: true
                            }).on('changeDate', function (ev) {

                                if ($(this).parents('form')) {
                                    $(this).parents('form').bootstrapValidator('revalidateField', $(this));
                                }

                            });
                            $(".datePicker").datepicker('setStartDate', '@System.DateTime.Now.ToString("yyyy-MM-dd")');
                            $('.searchingDropdown').select2();
                        }

                    }
                });


                //var r = elem.id;
                //$('#hidId').val(r);
                //$('#ActionId').val(2);
                //$('#btnSave').html("<i class='fa fa-edit'></i> Update");
                //$('#hidId').val($('#tdId' + r).text().trim());


                //$('#txtOrderDate').datepicker('setDate', $('#tdOrderDate' + r).text().trim());
                //$('#ddlCurrency').val($('#tdCurrencyId' + r).text().trim());
                //$('#txtTermsAndCondition').val($('#tdTAndC' + r).text().trim());

                //$('#txtDescription').val($('#tdDescription' + r).text().trim());
                //$('#ddlSupplier').val($('#tdSupplierId' + r).text().trim());
                //$('#ddlEmployee').val($('#tdEmployeeId' + r).text().trim());
                //$("#hdfDepartmentId").val($('#tdDepartmentId' + r).text().trim());
                //$('#txtDepartmentName').val($('#tdDepartmentName' + r).text().trim());
                //$('.ddlReset').trigger('change');

            }
        }

    function itemActionInfo(id, actionId, poActionId, poActionName) {
        if (id !== null && actionId !== null && poActionId !== null) {
            $('#hidId').val(id);
            $('#ActionId').val(actionId);
            $('#POActionId').val(poActionId);
            $("#lblPOActionName").html(poActionName);
        }
    }
        $("#btnClose").click(function (e) {
            e.preventDefault();

            $('#PurchaseInvoice').trigger("reset");



        });

        $("#ddlApprovedPR").change(function (e) {
            $('#divPOSlaveList').empty();
            ///populate controls with data from PRSlave
            $.ajax({
                type: "GET",
                url: "/Procurement/PurchaseInvoiceSlaveListPoWise?id=" + $("#ddlApprovedPR :selected").val(),
                datatype: "Json",
                success: function (data) {
                    if (data) {
                        $('#divPOSlaveList').html(data);
                        $('.formValidator').bootstrapValidator();
                        $('.datePicker').datepicker({
                            format: "yyyy-mm-dd",
                            // format: "d/m/yy",
                            autoclose: true
                        }).on('changeDate', function (ev) {

                            if ($(this).parents('form')) {
                                $(this).parents('form').bootstrapValidator('revalidateField', $(this));
                            }

                        });

                        $('.searchingDropdown').select2();

                        $("#tblPOSlaveList").DataTable({
                            "paging": false
                        });
                    }

                }
            });
        });

    </script>
}

Erp.App/Views/Procurement/PurchaseInvoice.cshtml
@{
    ViewData["Title"] = "Supplier Invoice";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var tdOrderId = "tdOrderId";
    var tdSupplierName = "tdSupplierName";
    var tdCreationDate = "tdCreationDate";
    var tdOrderDate = "tdOrderDate";
    var tdTAndC = "tdTAndC";
    var tdStatusName = "tdStatusName";
    var tdCreatedBy = "tdCreatedBy";
    var tdPOID = "tdPOID";
    var PIStatus = Model.AuthorizationStatus;

}
@model Erp.Core.Services.Procurement.VMPurchaseInvoice

<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="box">
            <div class="box-header custom bg-success">
                @{ if (Model.Status == Erp.Core.Services.PurchaseInvoiceStatusEnum.Closed || Model.Status == Erp.Core.Services.PurchaseInvoiceStatusEnum.Draft)
                    {
                        <h4>
                            <label>Supplier Invoice [ @PIStatus ]</label>
                        </h4>
                    }
                }
            </div>
            <div class="box-body">
                @if (Model.Status == Erp.Core.Services.PurchaseInvoiceStatusEnum.Draft)
                {
                    <div id="divEditPOInfo">
                        @{await Html.RenderPartialAsync("_PurchaseInvoiceSpecific");}
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="box">
            <div class="box-body">
                <div class="table-responsive">
                    <table id="tableABC" class="table table-striped text-nowrap">
                        <thead>
                            <tr>
                                <th>SL</th>
                                <th>Invoice Id</th>
                                <th>Invoice Origin</th>
                                <th>Invoice Date</th>
                                <th>Creation Date</th>
                                <th>Created By</th>
                                <th>Supplier</th>
                                <th>PO Id</th>
                                <th>Payment Method</th>
                                <th>Authorization Status</th>
                                <th class="hidden-print">Action</th>
                            </tr>
                        </thead>
                        @{int sl = 0;}
                        <tbody>
                            @foreach (var item in Model.DataList)
                            {
                            <tr>
                                <td>@(++sl)</td>
                                <td id="@tdOrderId@item.ID">@item.CID</td>
                                <td>@item.OriginTypeName</td>
                                <td id="@tdOrderDate@item.ID">@item.InvoiceDateTableString</td>
                                <td id="@tdCreationDate@item.ID">@item.CreationDateTableString</td>
                                <td id="@tdCreatedBy@item.ID">@item.CreatedBy</td>
                                <td id="@tdSupplierName@item.ID">@item.VMSupplierName</td>
                                <td id="@tdPOID@item.ID">@item.POCID</td>
                                <td id="@tdTAndC@item.ID">@item.PaymentMethodName</td>
                                <td id="@tdStatusName@item.ID">@item.AuthorizationStatus</td>
                                <td class="hidden-print">
                                    @{ if (item.Status == Erp.Core.Services.PurchaseInvoiceStatusEnum.Draft)
                                        {
                                            <a id="@item.ID" onclick=" menuinfo(this);" class="linkPointer" data-toggle="modal" data-target="#exampleModal" title="Edit"
                                               data-placement="top">
                                                <i class="glyphicon glyphicon-pencil" aria-hidden="true"></i>
                                            </a>
                                            <a id="@item.ID" onclick="itemActionInfo(@item.ID,3,@((int)Erp.Core.Services.PurchaseInvoiceActionEnum.Delete),'@Erp.Core.Services.BaseFunctionalities.GetEnumDescription(Erp.Core.Services.PurchaseInvoiceActionEnum.Delete)');" class="linkPointer" data-toggle="modal" data-target="#itemActionModal" title="Delete"
                                               data-placement="top">
                                                <i class="glyphicon glyphicon-trash" aria-hidden="true"></i>
                                            </a>
                                            @if (item.HasSlave)
                                            {
                                                <a id="@item.ID" onclick="itemActionInfo(@item.ID,4,@((int)Erp.Core.Services.PurchaseInvoiceActionEnum.Submit),'@Erp.Core.Services.BaseFunctionalities.GetEnumDescription(Erp.Core.Services.PurchaseInvoiceActionEnum.Submit)');" class="linkPointer" data-toggle="modal" data-target="#itemActionModal" title="Submit"
                                                   data-placement="top">
                                                    <i class="glyphicon glyphicon-ok" aria-hidden="true"></i>
                                                </a>
                                                <a id="@item.ID" onclick="itemActionInfo(@item.ID,4,@((int)Erp.Core.Services.PurchaseInvoiceActionEnum.Hold),'@Erp.Core.Services.BaseFunctionalities.GetEnumDescription(Erp.Core.Services.PurchaseInvoiceActionEnum.Hold)');" class="linkPointer" data-toggle="modal" data-target="#itemActionModal" title="Hold"
                                                   data-placement="top">
                                                    <i class="glyphicon glyphicon-pause" aria-hidden="true"></i>
                                                </a>
                                                <a id="@item.ID" onclick="itemActionInfo(@item.ID,4,@((int)Erp.Core.Services.PurchaseInvoiceActionEnum.Cancel),'@Erp.Core.Services.BaseFunctionalities.GetEnumDescription(Erp.Core.Services.PurchaseInvoiceActionEnum.Cancel)');" class="linkPointer" data-toggle="modal" data-target="#itemActionModal" title="Cancel"
                                                   data-placement="top">
                                                    <i class="glyphicon glyphicon-ban-circle" aria-hidden="true"></i>
                                                </a>

                                                <a id="@item.ID" onclick="itemActionInfo(@item.ID,4,@((int)Erp.Core.Services.PurchaseInvoiceActionEnum.Close),'@Erp.Core.Services.BaseFunctionalities.GetEnumDescription(Erp.Core.Services.PurchaseInvoiceActionEnum.Close)');" class="linkPointer" data-toggle="modal" data-target="#itemActionModal" title="Close"
                                                   data-placement="top">
                                                    <i class="glyphicon glyphicon-remove" aria-hidden="true"></i>
                                                </a>
                                            }
                                        }
                                    }
                                    @if (item.Status == Erp.Core.Services.PurchaseInvoiceStatusEnum.Draft)
                                    {
                                        <a id="@item.ID" class="linkPointer" href="~/Procurement/PurchaseInvoiceDetails/@item.ID" title="View & Edit Detail"
                                           data-placement="top">
                                            <i class="glyphicon glyphicon-zoom-in" aria-hidden="true"></i>
                                        </a>
                                    }
                                    else
                                    {
                                        <a id="@item.ID" class="linkPointer" href="~/Procurement/PurchaseInvoiceDetails/@item.ID" title="View Detail"
                                           data-placement="top">
                                            <i class="glyphicon glyphicon-zoom-in" aria-hidden="true"></i>
                                        </a>
                                    }
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@using (Html.BeginForm("PurchaseInvoice", "Procurement", FormMethod.Post, new { id = "PurchaseInvoice", @class = "formValidator", onreset = "resetDDL();" }))
{
    @Html.HiddenFor(model => model.ID, new { Value = "", id = "hidId" })
    @Html.HiddenFor(model => model.ActionId, new { Value = "", id = "ActionId" })
    @Html.HiddenFor(model => model.InvoiceActionId, new { Value = "", id = "POActionId" })
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="modal fade" id="itemActionModal" data-toggle="modal" data-backdrop="static" data-keyboard="false" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close pull-right" data-dismiss="modal" aria-label="Close">
                        &times;
                    </button>
                    <h5 class="modal-title"><b>Supplier Invoice</b></h5>

                </div>
                <div class="modal-body">
                    <div style="text-align:center">
                        <h3>Are you sure to <label id="lblPOActionName"></label>?</h3>
                    </div>

                </div>

                <div class="modal-footer">
                    <button type="button" id="btnClose" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" id="btnDelete" class="deleteId btn btn-primary"><i class="glyphicon glyphicon-check"></i> Confirm</button>
                </div>
            </div>
        </div>
    </div>
}

@section scripts {

    <script type="text/javascript">
        $(document).ready(function () {
            $('.formValidator').bootstrapValidator();
            $(".datePicker").datepicker('setStartDate', '@System.DateTime.Now.ToString("yyyy-MM-dd")');
        });

        function resetDDL() {
            $('#hidId').empty();
            $('#ActionId').val(1);
            $('#btnSave').html("<i class='fa fa-floppy-o'></i>&nbsp;Save");
            $('.ddlReset').val('').trigger('change');
            $('#PurchaseInvoice').bootstrapValidator("resetForm", true);
        }

        function menuinfo(elem) {
            if (elem !== null) {

                $.ajax({
                    type: "GET",
                    url: "/Procurement/PurchaseInvoiceSpecific?id=" + elem.id,
                    datatype: "Json",
                    success: function (data) {
                        if (data) {
                            $('#divEditPOInfo').html(data);
                            $('.formValidator').bootstrapValidator();
                            $('.datePicker').datepicker({
                                format: "yyyy-mm-dd",
                                autoclose: true
                            }).on('changeDate', function (ev) {
                                if ($(this).parents('form')) {
                                    $(this).parents('form').bootstrapValidator('revalidateField', $(this));
                                }
                            });
                            $(".datePicker").datepicker('setStartDate', '@System.DateTime.Now.ToString("yyyy-MM-dd")');
                            $('.searchingDropdown').select2();
                        }
                    }
                });
            }
        }

    function itemActionInfo(id, actionId, poActionId, poActionName) {
        if (id !== null && actionId !== null && poActionId !== null) {
            $('#hidId').val(id);
            $('#ActionId').val(actionId);
            $('#POActionId').val(poActionId);
            $("#lblPOActionName").html(poActionName);
        }
    }
        $("#btnClose").click(function (e) {
            e.preventDefault();
            $('#PurchaseInvoice').trigger("reset");
        });
    </script>
}